<?php

namespace Application\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagensRepository extends EntityRepository
{
}
