<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Imagens extends \Application\Entity\Imagens implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdimagen()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idimagen"];
        }
        $this->__load();
        return parent::getIdimagen();
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function getDescricao()
    {
        $this->__load();
        return parent::getDescricao();
    }

    public function getSrc()
    {
        $this->__load();
        return parent::getSrc();
    }

    public function getCategoria()
    {
        $this->__load();
        return parent::getCategoria();
    }

    public function getFormato()
    {
        $this->__load();
        return parent::getFormato();
    }

    public function getSubcategoria()
    {
        $this->__load();
        return parent::getSubcategoria();
    }

    public function getTipos()
    {
        $this->__load();
        return parent::getTipos();
    }

    public function setIdimagen($idimagen)
    {
        $this->__load();
        return parent::setIdimagen($idimagen);
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function setDescricao($descricao)
    {
        $this->__load();
        return parent::setDescricao($descricao);
    }

    public function setSrc($src)
    {
        $this->__load();
        return parent::setSrc($src);
    }

    public function setCategoria($categoria)
    {
        $this->__load();
        return parent::setCategoria($categoria);
    }

    public function setFormato($formato)
    {
        $this->__load();
        return parent::setFormato($formato);
    }

    public function setSubcategoria($subcategoria)
    {
        $this->__load();
        return parent::setSubcategoria($subcategoria);
    }

    public function setTipos($tipos)
    {
        $this->__load();
        return parent::setTipos($tipos);
    }

    public function getWidth()
    {
        $this->__load();
        return parent::getWidth();
    }

    public function getHeight()
    {
        $this->__load();
        return parent::getHeight();
    }

    public function setWidth($width)
    {
        $this->__load();
        return parent::setWidth($width);
    }

    public function setHeight($height)
    {
        $this->__load();
        return parent::setHeight($height);
    }

    public function getPeso()
    {
        $this->__load();
        return parent::getPeso();
    }

    public function setPeso($peso)
    {
        $this->__load();
        return parent::setPeso($peso);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idimagen', 'titulo', 'descricao', 'src', 'peso', 'width', 'height', 'categoria', 'formato', 'subcategoria', 'tipos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}