<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Subcategoria extends \Application\Entity\Subcategoria implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdsubcategoria()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idsubcategoria"];
        }
        $this->__load();
        return parent::getIdsubcategoria();
    }

    public function getTitulo()
    {
        $this->__load();
        return parent::getTitulo();
    }

    public function getSlug()
    {
        $this->__load();
        return parent::getSlug();
    }

    public function getCategoriacategoria()
    {
        $this->__load();
        return parent::getCategoriacategoria();
    }

    public function setIdsubcategoria($idsubcategoria)
    {
        $this->__load();
        return parent::setIdsubcategoria($idsubcategoria);
    }

    public function setTitulo($titulo)
    {
        $this->__load();
        return parent::setTitulo($titulo);
    }

    public function setSlug($slug)
    {
        $this->__load();
        return parent::setSlug($slug);
    }

    public function setCategoriacategoria($categoriacategoria)
    {
        $this->__load();
        return parent::setCategoriacategoria($categoriacategoria);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idsubcategoria', 'titulo', 'slug', 'categoriacategoria');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}