<style>
body{
    background: url('./img/image.jpg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;  
}

</style>

<div class="bs-example">
      <div class="jumbotron" style="opacity:0.9;">
      	<center>
        <h1>Spicy Store</h1>
        <p>Encontre diversas imagens no Spicy Store</p>
   
   <form class="form-inline" role="form">
  <div class="form-group">
    <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Pesquisar uma imagem">
  </div>
  <button type="submit" class="btn btn-success">Buscar</button>
</form>
      	</center>
      </div>
    </div>